##########################
# Container configuration.

# Complete list of all available properties: https://docs.platform.sh/create-apps/app-reference.html

# A unique name for the app. Must be lowercase alphanumeric characters. Changing the name destroys data associated
# with the app.
name: tystar_cz

variables:
    env:
        ENV: 'production'
        SECRET_KEY: '(bh#usix2x!!2f5h5cb@-&7m&(cewcp=81!ycahlyxqz+3g$7k'

# The type of the application to build
type: 'python:3.12'

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
# More information: https://docs.platform.sh/create-apps/app-reference.html#relationships
relationships:
    database: "db:postgresql"

# The build-time dependencies of the app.
dependencies:
    python3:
       pipenv: "2023.12.1"

# The size of the persistent disk of the application (in MB)
disk: 1024
size: M

# Your app's configuration when it's exposed to the web.
web:
    upstream:
        # Whether your app should speak to the webserver via TCP or Unix socket. Defaults to tcp
        socket_family: unix
    commands:
        # The exact command varies based on the server you use

        # # 1) ASGI: daphne
        # start: "pipenv run daphne app.asgi:application"
        # # 2) ASGI: uvicorn
        # start: "pipenv run gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b unix:$SOCKET app.wsgi:application"
        # # 3) ASGI: hypercorn
        # start: "pipenv run hypercorn app.asgi:application"
        # 4) WSGI: gunicorn
        start: "pipenv run gunicorn -w 4 -b unix:$SOCKET base.wsgi:application"
    # Each key in locations is a path on your site with a leading /.
    # More information: https://docs.platform.sh/create-apps/app-reference.html#locations
    locations:
        "/":
            # Whether to forward disallowed and missing resources from this location to the app. A string is a path
            # with a leading / to the controller, such as /index.php.
            passthru: true
        "/static":
            # The directory to serve static assets for this location relative to the app’s root directory. Must be an
            # actual directory inside the root directory.
            root: "my_app/static"
            # The number of seconds whitelisted (static) content should be cached.
            expires: 1h
            # Whether to allow serving files which don’t match a rule.
            allow: true
hooks:
  # The build hook is run after any build flavor.
  # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#build-hook
  build: |
    set -eu

    # Download the latest version of pip
    python3.12 -m pip install --upgrade pip

    # Install dependencies
    pipenv install --deploy

    # Collect static assets
    pipenv run python manage.py collectstatic    

  # The deploy hook is run after the app container has been started, but before it has started accepting requests.
  # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#deploy-hook
  deploy: pipenv run python manage.py migrate