repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ['-l 119']
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0'
    hooks:
      - id: prettier
        entry: prettier --write --single-quote --trailing-comma=all
        files: "\\.(\
          |graphql|gql\
          |json\
          |yaml|yml\
          )$"
  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: ['--profile', 'black']
exclude: '.*/migrations|staticfiles/|.*.po|.*.mo'
# repos:
#   - repo: https://github.com/prettier/pre-commit
#     rev: 57f39166b5a5a504d6808b87ab98d41ebf095b46
#     hooks:
#       - id: prettier
#         entry: prettier --write --single-quote --trailing-comma=all
#         files: "\\.(\
#           |graphql|gql\
#           |json\
#           |yaml|yml\
#           )$"
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.3.0
#     hooks:
#       - id: trailing-whitespace
#       - id: end-of-file-fixer

# exclude: '.*/migrations|staticfiles/|.*.po|.*.mo'
