# Generated by Django 2.2 on 2019-04-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190413_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source',
            new_name='Resource',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='source',
            new_name='resource',
        ),
    ]
