# Generated by Django 2.2 on 2019-04-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190413_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
