# Generated by Django 2.2 on 2019-04-17 09:33

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190417_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=30, populate_from=['name'], unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=30, populate_from=['title'], unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=30, populate_from=['name'], unique=True),
        ),
    ]
