# Generated by Django 2.2 on 2019-04-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190417_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
