# Generated by Django 5.0.2 on 2024-03-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_category_tag_article_categories_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('github_url', models.URLField(unique=True)),
                ('image', models.FileField(blank=True, upload_to='project_images/')),
                ('technologies', models.ManyToManyField(blank=True, to='my_site.tag')),
            ],
        ),
    ]
